### ISSUE TITLE
python-3.9 error during exception handling

### ISSUE THREAD

**Issue by KineticCookie** [open-runtimes/open-runtimes#151]
Python 3.9 image doesn't handle exceptions properly.
Code that handles exceptions fails with `TypeError: can only concatenate str (not "generator") to str`

Example traceback:
```
...
Pydantic parsing exception, nothing extraordinary
...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/src/userlib/runtime-env/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/src/userlib/runtime-env/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/src/userlib/runtime-env/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/src/userlib/runtime-env/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/src/server.py", line 90, in handler
    "stderr": usererr.getvalue() + "\n" + traceback.TracebackException.from_exception(e).format()
TypeError: can only concatenate str (not "generator") to str
```

**Comment by stnguyen90** [comment]
@KineticCookie, thanks for raising this issue! 🙏🏼 Would you please share your code, so we have a better idea about what causes this?

**Comment by stnguyen90** [comment]
@KineticCookie are you still facing this problem? If so, please provide the info requested:

> Would you please share your code, so we have a better idea about what causes this?

Please keep in mind I'll need to close this due to inactivity soon if there's no response.
